apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wg-control-plane.fullname" . }}-app
  labels:
    {{- include "wg-control-plane.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ include "wg-control-plane.dbPassword" . | trim | quote }}
  mail-password: {{ .Values.env.mailPassword | quote }}
  app-internal-api-key: {{ .Values.env.appInternalApiKey | quote }}
  admin-password: {{ .Values.env.adminPassword | quote }}
